version: '3.4'
services:
  qgis-server:
    build:
      context: proxy
    volumes:
      - ./proxy:/app
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678

  worker:
    build:
      context: worker
    volumes:
      - ./worker:/app
      - ./projects:/io/projects
      - ./scripts:/io/scripts
    restart:
      unless-stopped
    deploy:
      replicas: 1
