version: "3.9"

services:
  qgis-server:
    build:
      context: proxy
    ports:
      - "8000:8000"
    volumes:
      - ./proxy:/app
    restart:
      unless-stopped

  worker:
    build:
      context: worker
    volumes:
      - ./worker:/app
      - ./projects:/io/data
      - ./scripts:/io/scripts
    restart:
      unless-stopped
    deploy:
      replicas: 5

  redis:
    image: redis:7.0.11-alpine
