version: "3.9"

services:
  qgis-server:
    build:
      context: proxy
    ports:
      - "8000:8000"
    volumes:
      - ./proxy:/app
    restart:
      unless-stopped
    environment:
     # Timeout in seconds. After this time, jobs will fail, regardless if they have been tried enough times
     # E.g. when no worker is around at all
      TIMEOUT: 60

  worker:
    build:
      context: worker
    volumes:
      - ./worker:/app
      - ./projects:/io/data
      - ./scripts:/io/scripts
    restart:
      unless-stopped
    deploy:
      replicas: 2
    environment:
      # Timeout in seconds after which the worker should give up and restart the job
      # TODO ... In this case we assume that QGIS is dead. So we could also just immediately die and exit and restart
      # the container
      TIMEOUT: 10
      # Maximum retry count for failed jobs
      RETRIES: 10
      # Comma separated list of projects
      PRELOAD_PROJECTS: 'simple_bee_farming'

  redis:
    image: redis:7.0.11-alpine
